### ISSUE TITLE
what about headers

### ISSUE THREAD

**Issue by bnomei** [getkirby/staticache#7]
like CSP headers. currently i solve this with a plugin of mine. how would that be possible with raw html? would i need to export them to apache and nginx?

**Comment by iskrisis** [comment]
I think so. There is no php execution. The only way i can imagine this could happen would be something like [mod_asis in Apache](https://httpd.apache.org/docs/current/mod/mod_asis.html) (there is probably nginx equivalent). Where you save and serve anything into the file including the headers.

This makes sense only if you need per page headers which people probably wont? Adding the headers for the whole staticcache in webserver makes most sense. But we will need figure those configs because they would be more complicated.

**Comment by bnomei** [comment]
my plugin is a wrapper around another lib and that can export those.
https://github.com/paragonie/csp-builder#save-a-csp-header-for-configuring-apachenginx
i also created helper so make them a bit easier to use with the plugin
https://github.com/bnomei/kirby3-security-headers/blob/3c987c013d6ba2e30ebad5f9c545388d6d738b6a/classes/SecurityHeaders.php#L197

i guess its more about **knowing that CSP will not work for static served pages** and how to fix it.

**Comment by lukasbestle** [comment]
Never heard about `mod_asis` until now. That's actually pretty clever. 🤯

We could make this configurable. So those who have access to `mod_asis` or similar could get the full response exported. Otherwise the default would be just the body.

**Comment by bnomei** [comment]
my fork can cache and dump the headers but only if php mode is used.
https://github.com/bnomei/kirby3-staticache/blob/ad6e38506bfde939f3a36b7eef4c46ac02cec712/classes/StatiCache.php#L56

since the "php mode" happens before kirby is booted it should still be very fast.

**Comment by lukasbestle** [comment]
✅
